server:
  port: 8082

spring:
  application:
    name: carrito-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 0

spring:
  jpa:
    hibernate:
      ddl-auto: update
    datasource:
      url: jdbc:mysql://localhost:3307/tienda_carrito?serverTimezone=UTC
      username: root
      password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect