server:
  port: 8084

spring:
  application:
    name: ventas-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: ${url}
    username: ${username}
    password: ${password}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-sv:8761/eureka/

eureka.instance:
  lease-renewal-interval-in-seconds: 0
